### ISSUE TITLE
Error: This callback function has already been called by someone else; it can only be called one time.

### ISSUE THREAD

**Issue by b-a-k-u-a-n** [kovalev-sergey/homebridge-sony-audio#41]
Hi,

The plugin keeps throwing the following error and essentially causes Homebridge to restart.

What can I do to get rid of this problem please?

Log:

23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:442:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:450:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:442:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:450:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:442:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:450:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:442:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:450:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:442:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:450:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:442:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-sony-audio/src/sonyAudioAccessory.ts:450:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/02/2024, 20:26:46] Got SIGTERM, shutting down Homebridge...

**Comment by kovalev-sergey** [comment]
Fixed. The handlers chained `promise.then(callback).catch(callback)`, so as soon as the first callback call threw — HAP wraps callbacks in `once()` — the rejection handler called the very same callback again, producing this error on every read of the input visibility characteristics (`sonyAudioAccessory.ts:442/450`).

Callback invocation is now guarded and the fulfilment path is separated from the rejection path, so every HAP callback is answered exactly once. Regression tests were added in #54 (they fail on the previous code). Ships in 2.0.1.
